In [1]:
!pip install mlkit

Requirement already satisfied: mlkit in c:\ml_env\lib\site-packages (0.0.1)

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import random

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/Codecademy/datasets/master/streeteasy/streeteasy.csv")
df = pd.get_dummies(df, dtype=int)
df.drop(["rental_id", "building_id"], axis=1, inplace=True)
df.head()

,rent,bedrooms,bathrooms,size_sqft,min_to_subway,floor,building_age_yrs,no_fee,has_roofdeck,has_washer_dryer,...,submarket_Northeast Queens,submarket_Northwest Brooklyn,submarket_Northwest Queens,submarket_Prospect Park,submarket_South Brooklyn,submarket_South Queens,submarket_The Rockaways,borough_Brooklyn,borough_Manhattan,borough_Queens
0,2550,0.0,1,480,9,2.0,17,1,1,0,...,0,0,0,0,0,0,0,0,1,0
1,11500,2.0,2,2000,4,1.0,96,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,3000,3.0,1,1000,4,1.0,106,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,4500,1.0,1,916,2,51.0,29,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,4795,1.0,1,975,3,8.0,31,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [4]:
df.describe()

,rent,bedrooms,bathrooms,size_sqft,min_to_subway,floor,building_age_yrs,no_fee,has_roofdeck,has_washer_dryer,...,submarket_Northeast Queens,submarket_Northwest Brooklyn,submarket_Northwest Queens,submarket_Prospect Park,submarket_South Brooklyn,submarket_South Queens,submarket_The Rockaways,borough_Brooklyn,borough_Manhattan,borough_Queens
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,4536.920800,1.395700,1.321600,920.101400,5.079200,10.190200,52.093200,0.429600,0.12860,0.133800,...,0.010400,0.062200,0.053000,0.016200,0.023800,0.002600,0.000200,0.202600,0.707800,0.089600
std,2929.838953,0.961018,0.565542,440.150464,5.268897,10.565361,40.224501,0.495069,0.33479,0.340471,...,0.101459,0.241543,0.224056,0.126257,0.152441,0.050929,0.014142,0.401977,0.454819,0.285636
min,1250.000000,0.000000,0.000000,250.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2750.000000,1.000000,1.000000,633.000000,2.000000,3.000000,12.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3600.000000,1.000000,1.000000,800.000000,4.000000,6.000000,44.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,5200.000000,2.000000,2.000000,1094.000000,6.000000,14.000000,89.000000,1.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,20000.000000,5.000000,5.000000,4800.000000,51.000000,83.000000,180.000000,1.000000,1.00000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
X = df.drop("rent", axis=1).to_numpy()
y = df["rent"].to_numpy()

In [6]:
from mlkit.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=42)

In [7]:
from mlkit.tune import ModelTuner
from mlkit.linear_model import LinearRegression, LogisticRegression
from mlkit.model_selection import KFold

tuner = ModelTuner(model = LinearRegression())

best_model = tuner.fit(X_train, y_train)

[I 2024-12-02 14:24:02,195] A new study created in memory with name: tuner_study

Starting optimization process...

  0%|          | 0/10000 [00:00<?, ?it/s]

[I 2024-12-02 14:29:25,805] Trial 0 finished with value: -916.6187758879732 and parameters: {'n_iters': 3000, 'lr': 0.08644435211907153, 'reg_mode': 'elasticnet', 'reg_strength': 0.0018605562482929894, 'reg_ratio': 0.3836216458939058, 'method': 'sgd', 'batch_size': 256, 'scaler': <mlkit.preprocessing.scalers.MinMaxScaler object at 0x000001451E96FDC0>, 'verbose': 0}. Best is trial 0 with value: -916.6187758879732.
[I 2024-12-02 14:34:21,200] Trial 1 finished with value: -821.7991886314707 and parameters: {'n_iters': 7000, 'lr': 0.017593889297907457, 'reg_mode': 'elasticnet', 'reg_strength': 0.003019788058084728, 'reg_ratio': 0.5907841220106307, 'method': 'sgd', 'batch_size': 128, 'scaler': <mlkit.preprocessing.scalers.StandardScaler object at 0x000001451CF298B0>, 'verbose': 0}. Best is trial 1 with value: -821.7991886314707.
[I 2024-12-02 14:39:36,239] Trial 2 finished with value: -821.4513744857107 and parameters: {'n_iters': 5000, 'lr': 0.015223753824820156, 'reg_mode': 'l1', 'reg_strength': 0.0025652412876776822, 'reg_ratio': 0.5584685781527804, 'method': 'sgd', 'batch_size': 256, 'scaler': <mlkit.preprocessing.scalers.StandardScaler object at 0x000001451CB80D60>, 'verbose': 0}. Best is trial 2 with value: -821.4513744857107.
[I 2024-12-02 14:40:05,991] Trial 3 finished with value: -821.5997710633237 and parameters: {'n_iters': 9000, 'lr': 0.08079510647011927, 'reg_mode': 'l1', 'reg_strength': 0.002316573878435784, 'reg_ratio': 0.4747573757536239, 'method': 'gd', 'batch_size': 256, 'scaler': <mlkit.preprocessing.scalers.StandardScaler object at 0x000001451CF64C70>, 'verbose': 0}. Best is trial 2 with value: -821.4513744857107.
[I 2024-12-02 14:40:16,071] Trial 4 finished with value: -846.3991131458057 and parameters: {'n_iters': 3000, 'lr': 0.06094942920624645, 'reg_mode': 'l1', 'reg_strength': 0.0018938304059728218, 'reg_ratio': 0.21410317805994966, 'method': 'gd', 'batch_size': 256, 'scaler': <mlkit.preprocessing.scalers.MinMaxScaler object at 0x000001451C848190>, 'verbose': 0}. Best is trial 2 with value: -821.4513744857107.
[I 2024-12-02 14:40:52,944] Trial 5 finished with value: -858.466885422665 and parameters: {'n_iters': 11000, 'lr': 0.013215496663646055, 'reg_mode': 'elasticnet', 'reg_strength': 0.003916295934127343, 'reg_ratio': 0.23768127353442278, 'method': 'gd', 'batch_size': 128, 'scaler': <mlkit.preprocessing.scalers.MinMaxScaler object at 0x000001451CDF4A60>, 'verbose': 0}. Best is trial 2 with value: -821.4513744857107.
[I 2024-12-02 14:45:40,251] Trial 6 finished with value: -821.8009505711598 and parameters: {'n_iters': 7000, 'lr': 0.03547247680522859, 'reg_mode': 'l1', 'reg_strength': 0.0026491244639340727, 'reg_ratio': 0.7160751695442966, 'method': 'sgd', 'batch_size': 128, 'scaler': <mlkit.preprocessing.scalers.StandardScaler object at 0x000001451CD4F910>, 'verbose': 0}. Best is trial 2 with value: -821.4513744857107.
[I 2024-12-02 14:50:44,552] Trial 7 finished with value: -973.5210302175188 and parameters: {'n_iters': 13000, 'lr': 0.04061161990931187, 'reg_mode': 'elasticnet', 'reg_strength': 0.003477600169598761, 'reg_ratio': 0.5310443558817404, 'method': 'sgd', 'batch_size': 128, 'scaler': <mlkit.preprocessing.scalers.MinMaxScaler object at 0x000001451CBD2040>, 'verbose': 0}. Best is trial 2 with value: -821.4513744857107.
[I 2024-12-02 14:55:23,460] Trial 8 finished with value: -973.4796196972002 and parameters: {'n_iters': 15000, 'lr': 0.032843457459335236, 'reg_mode': 'l2', 'reg_strength': 0.0051442720759271605, 'reg_ratio': 0.25340848709805336, 'method': 'sgd', 'batch_size': 128, 'scaler': <mlkit.preprocessing.scalers.MinMaxScaler object at 0x000001451CDF4100>, 'verbose': 0}. Best is trial 2 with value: -821.4513744857107.

Finished tuning. Best params are:
{'n_iters': 5000, 'lr': 0.015223753824820156, 'method': 'sgd', 'batch_size': 256, 'scaler': <mlkit.preprocessing.scalers.StandardScaler object at 0x000001451C8A2220>, 'verbose': 0, 'reg': ('l1', 0.0025652412876776822)}

Retraining best model on entire dataset.
Done. ðŸ˜„

In [8]:
best_model.score(X_test, y_test)

{'mae': 767.1589906755347,
 'mse': 1352538.7874977866,
 'rmse': 1162.9870108895398,
 'r2': 0.7952123086319922}

In [9]:
tuner.study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_batch_size,params_lr,params_method,params_n_iters,params_reg_mode,params_reg_ratio,params_reg_strength,params_scaler,params_verbose,state
0,0,-916.618776,2024-12-02 14:24:02.223369,2024-12-02 14:29:25.804452,0 days 00:05:23.581083,256,0.086444,sgd,3000,elasticnet,0.383622,0.001861,<mlkit.preprocessing.scalers.MinMaxScaler obje...,0,COMPLETE
1,1,-821.799189,2024-12-02 14:29:25.873956,2024-12-02 14:34:21.199578,0 days 00:04:55.325622,128,0.017594,sgd,7000,elasticnet,0.590784,0.003020,<mlkit.preprocessing.scalers.StandardScaler ob...,0,COMPLETE
2,2,-821.451374,2024-12-02 14:34:21.255704,2024-12-02 14:39:36.239624,0 days 00:05:14.983920,256,0.015224,sgd,5000,l1,0.558469,0.002565,<mlkit.preprocessing.scalers.StandardScaler ob...,0,COMPLETE
3,3,-821.599771,2024-12-02 14:39:36.288528,2024-12-02 14:40:05.990654,0 days 00:00:29.702126,256,0.080795,gd,9000,l1,0.474757,0.002317,<mlkit.preprocessing.scalers.StandardScaler ob...,0,COMPLETE
4,4,-846.399113,2024-12-02 14:40:06.039429,2024-12-02 14:40:16.071386,0 days 00:00:10.031957,256,0.060949,gd,3000,l1,0.214103,0.001894,<mlkit.preprocessing.scalers.MinMaxScaler obje...,0,COMPLETE
5,5,-858.466885,2024-12-02 14:40:16.125578,2024-12-02 14:40:52.944961,0 days 00:00:36.819383,128,0.013215,gd,11000,elasticnet,0.237681,0.003916,<mlkit.preprocessing.scalers.MinMaxScaler obje...,0,COMPLETE
6,6,-821.800951,2024-12-02 14:40:52.997345,2024-12-02 14:45:40.250970,0 days 00:04:47.253625,128,0.035472,sgd,7000,l1,0.716075,0.002649,<mlkit.preprocessing.scalers.StandardScaler ob...,0,COMPLETE
7,7,-973.521030,2024-12-02 14:45:40.300360,2024-12-02 14:50:44.551777,0 days 00:05:04.251417,128,0.040612,sgd,13000,elasticnet,0.531044,0.003478,<mlkit.preprocessing.scalers.MinMaxScaler obje...,0,COMPLETE
8,8,-973.479620,2024-12-02 14:50:44.598099,2024-12-02 14:55:23.460014,0 days 00:04:38.861915,128,0.032843,sgd,15000,l2,0.253408,0.005144,<mlkit.preprocessing.scalers.MinMaxScaler obje...,0,COMPLETE